let products=[
 {name:'9PM Elixir',folder:'product 9PM Elixir',images:['1.jpg','2.jpg'],price:2300,tag:'Signature',description:'A rich, lasting expression with luminous florals, warm woods, and a golden trail that stays long after you leave.',sizes:['30 ml','50 ml'],sizePrices:{'30 ml':1150,'50 ml':2300}},
 {name:'9PM Rebel',folder:'product 9PM Rebel',images:['1.jpg','2.jpg','3.jpg'],price:2550,tag:'Best seller',description:'Confident and magnetic. A spirited blend made for nights that deserve to be remembered.',sizes:['30 ml','50 ml'],sizePrices:{'30 ml':1350,'50 ml':2550}},
 {name:'Creed Aventus',folder:'product Creed Aventus',images:['1.png','2.png','3.jfif'],price:2700,tag:'Bestseller',description:'Bold character meets polished refinement in this confident, long-lasting signature.',sizes:['30 ml','50 ml'],sizePrices:{'30 ml':1400,'50 ml':2700}},
 {name:'Gucci Flora',folder:'product Gucci Flora',images:['1.jpg','2.jpg'],price:2400,tag:'New arrival',description:'A softly luminous floral composition with a fresh, graceful finish.',sizes:['30 ml','50 ml'],sizePrices:{'30 ml':1250,'50 ml':2400}},
 {name:'Hawas ice',folder:'product Hawas ice',images:['1.jfif','2.jpg','3.jpg'],price:2600,tag:'Fresh',description:'Cool, energetic, and clean. A crisp scent for days that move fast.',sizes:['30 ml','50 ml'],sizePrices:{'30 ml':1350,'50 ml':2600}},
 {name:'Janan Sports',folder:'product Janan Sports',images:['1.jpeg','2.jpg','3.jpg'],price:2300,tag:'Everyday',description:'Bright citrus and smooth woods in an easy, active daily signature.',sizes:['30 ml','50 ml'],sizePrices:{'30 ml':1200,'50 ml':2300}},
 {name:'Marj',folder:'product Marj',images:['1.jfif','2.jpg','3.jpg'],price:2500,tag:'Popular',description:'A balanced, modern fragrance with an elegant warmth that wears beautifully.',sizes:['30 ml','50 ml'],sizePrices:{'30 ml':1300,'50 ml':2500}},
 {name:'Wisaal',folder:'product Wisaal',images:['1.jpg','2.jpg','3.jpg'],price:1800,tag:'New arrival',description:'Intimate florals and soft musk, composed for a quietly unforgettable presence.',sizes:['30 ml','50 ml'],sizePrices:{'30 ml':1000,'50 ml':1800}}
];
const image=(product,index=0)=>`${product.folder}/${product.images[index]}`;
let cart=JSON.parse(localStorage.getItem('abid-cart')||'[]');
let currentProduct=null;
let qty=1;
let selectedSize='50 ml';
const app=document.querySelector('#app');

function money(value){return `PKR ${Number(value).toLocaleString()}`}
function sizePrice(product,size='50 ml'){if(product?.sizePrices){return Number(product.sizePrices[size] ?? product.price ?? 0)}return Number(product?.price ?? 0)}
function card(product){
 const price=money(sizePrice(product,'50 ml'));
 return `<article class="product-card" data-product="${product.name}"><div class="product-image"><img src="${image(product)}" alt="${product.name} perfume" loading="lazy"><span class="product-tag">${product.tag}</span></div><div class="product-info"><h3>${product.name}</h3><p>Abid Fragrance · ${product.images.length} views</p><span class="price">${price}</span></div></article>`;
}
function home(){return `<section class="hero"><div class="hero-copy"><span class="eyebrow">The signature collection · 2026</span><h1>Wear your<br><em>presence.</em></h1><p>Discover expressive fragrances made to linger in the room and in memory. Crafted for the moments that become stories.</p><a class="button" href="#shop" data-route="shop">Explore perfumes <span>　→</span></a></div><div class="hero-image"></div></section><section class="section"><div class="section-head"><div><span class="eyebrow">The edit</span><h2>Most wanted</h2></div><a class="link-arrow" href="#shop" data-route="shop">View all perfumes　→</a></div><div class="products-grid">${products.slice(0,4).map(card).join('')}</div></section><section class="split-banner"><img src="${image(products[2])}" alt="Creed Aventus by Abid Fragrance" loading="lazy"><div class="split-copy"><span class="eyebrow">A modern classic</span><h2>Leave a<br>lasting mark.</h2><p>Every bottle is an invitation: to slow down, to feel more, and to make an entrance all your own.</p><a class="button light" href="#product/Creed%20Aventus" data-route="product" data-product-link="Creed Aventus">Discover the scent　→</a></div></section><section class="benefits"><div class="benefit"><b>01</b><div><h3>Long-lasting craft</h3><p>Concentrated compositions designed to carry you through the day.</p></div></div><div class="benefit"><b>02</b><div><h3>Made with intention</h3><p>Beautifully considered fragrances with an unmistakable point of view.</p></div></div><div class="benefit"><b>03</b><div><h3>Delivered with care</h3><p>Thoughtful packaging and dependable delivery to your doorstep.</p></div></div></section><section class="section"><div class="quote"><span class="eyebrow">The Abid feeling</span><p>“The best accessory is the trace of you that remains after you leave.”</p><cite>Abid Fragrance</cite></div></section>`}
function shop(){return `<section class="page-top"><span class="eyebrow">The collection</span><h1>All perfumes</h1><p>Eight signatures. One unmistakable point of view.</p></section><section class="section"><div class="shop-toolbar"><span>${products.length} fragrances</span><select aria-label="Sort perfumes"><option>Curated selection</option><option>Price: low to high</option><option>Price: high to low</option></select></div><div class="products-grid">${products.map(card).join('')}</div></section>`}
function productView(name){
 currentProduct=products.find(p=>p.name===decodeURIComponent(name))||products[0];
 qty=1;
 selectedSize='50 ml';
 const p=currentProduct;
 const displayedPrice=sizePrice(p,selectedSize);
 return `<div class="detail-view"><div class="gallery"><div class="thumbs">${p.images.map((_,i)=>`<button class="thumb ${i===0?'active':''}" data-index="${i}"><img src="${image(p,i)}" alt="${p.name} view ${i+1}"></button>`).join('')}</div><div class="gallery-main"><img id="main-product-image" src="${image(p)}" alt="${p.name} perfume"></div></div><div class="detail-copy"><span class="eyebrow">Abid Fragrance · ${p.tag}</span><h1>${p.name}</h1><span class="price">${money(displayedPrice)}</span><p>${p.description}</p><div class="detail-meta"><div><label>Concentration</label><strong>Eau de parfum</strong></div><div><label>Delivery</label><strong>Free delivery</strong></div><div><label>Returns</label><strong>10–15 days</strong></div></div><label class="eyebrow">Choose your size</label><div class="sizes">${(p.sizePrices?Object.keys(p.sizePrices):['30 ml','50 ml']).map(size=>`<button class="size ${size===selectedSize?'selected':''}" data-size="${size}">${size}</button>`).join('')}</div><div class="buy-row"><div class="quantity"><button data-quantity="-">−</button><span class="qty-value">1</span><button data-quantity="+">+</button></div><button class="button" data-add="${p.name}">Add to cart　→</button></div><button class="button light" style="margin-top:10px;width:100%" data-buy="${p.name}">Buy now</button></div></div><section class="section related"><div class="section-head"><div><span class="eyebrow">Keep exploring</span><h2>You may also like</h2></div></div><div class="products-grid">${products.filter(x=>x.name!==p.name).slice(0,4).map(card).join('')}</div></section>`;
}
function about(){return `<section class="text-page"><span class="eyebrow">Our story</span><h1>Fragrance with<br>something to say.</h1><p>Abid Fragrance began with a simple belief: scent is not decoration. It is atmosphere, memory, and the first impression you leave behind.</p><p>Our collection brings together expressive compositions for every kind of presence, from the first light of morning to the last song of the night. Each bottle is made to feel personal, polished, and entirely yours.</p><div class="story-grid"><img src="${image(products[0])}" alt="9PM Elixir fragrance"><img src="${image(products[6])}" alt="Marj fragrance"></div></section>`}
function contact(){return `<section class="text-page"><span class="eyebrow">We would love to hear from you</span><h1>Let's talk<br>fragrance.</h1><p>For product advice, order help, or simply to talk scent, our team is here.</p><div class="contact-links"><a class="contact-card" href="https://wa.me/message/E6YOADVJG4B6K1" target="_blank" rel="noopener"><span class="contact-icon whatsapp-icon">WA</span><span><small>WhatsApp</small><strong>Message us directly</strong></span><b>↗</b></a><a class="contact-card" href="mailto:abidfragrance977@gmail.com"><span class="contact-icon">✉</span><span><small>Email</small><strong>abidfragrance977@gmail.com</strong></span><b>↗</b></a><a class="contact-card" href="tel:+923199740620"><span class="contact-icon">☎</span><span><small>Call us</small><strong>03199740620</strong></span><b>↗</b></a></div><div class="contact-grid"><form id="contact-form"><div class="form-field"><label>Name</label><input required placeholder="Your name"></div><div class="form-field"><label>Email</label><input type="email" required placeholder="you@example.com"></div><div class="form-field"><label>Message</label><textarea required placeholder="Tell us what is on your mind..."></textarea></div><button class="button">Send message　→</button></form><div><div class="detail-meta" style="display:block"><label>Hours</label><strong>Monday – Saturday<br>10:00 am – 7:00 pm</strong><label style="margin-top:22px">Delivery & returns</label><strong>Free delivery available<br>10–15 days return policy</strong></div></div></div></section>`}
function checkout(){return `<section class="text-page"><span class="eyebrow">Complete your order</span><h1>Almost yours.</h1><div class="checkout-grid"><form id="checkout-form"><div class="form-field"><label>Full name</label><input required placeholder="Your name"></div><div class="form-field"><label>Phone number</label><input required placeholder="03xx xxxxxxx"></div><div class="form-field"><label>Delivery address</label><textarea required placeholder="House, street, city"></textarea></div><button class="button">Place order　→</button></form><div><h3>Order summary</h3>${cart.map(item=>`<div class="track-line"><span>${item.name} × ${item.quantity}</span><strong>${money(item.price*item.quantity)}</strong></div>`).join('')}<div class="cart-total"><strong>Total</strong><strong>${money(cart.reduce((sum,item)=>sum+item.price*item.quantity,0))}</strong></div></div></div></section>`}
function tracking(){return `<section class="text-page"><div class="tracking"><span class="eyebrow">Order tracking</span><h1>Where is it now?</h1><p>Enter your order number to see the latest delivery update.</p><form id="tracking-form"><div class="form-field"><label>Order number</label><input required placeholder="e.g. AF-1024"></div><button class="button">Track order　→</button></form><div id="track-result" class="track-result hidden"></div></div></section>`}
function render(){const hash=location.hash.slice(1)||'home';const [route,...rest]=hash.split('/');document.querySelector('.cart-panel')?.classList.remove('open');if(route==='product'){app.innerHTML=productView(rest.join('/')||products[0].name)}else if(route==='shop'){app.innerHTML=shop()}else if(route==='about'){app.innerHTML=about()}else if(route==='contact'){app.innerHTML=contact()}else if(route==='checkout'){app.innerHTML=checkout()}else if(route==='tracking'){app.innerHTML=tracking()}else{app.innerHTML=home()}window.scrollTo(0,0);bindPage();updateCart()}
function updateCart(){document.querySelector('.cart-count').textContent=cart.reduce((s,x)=>s+x.quantity,0)}
function toast(message){const el=document.querySelector('.toast');el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2400)}
function addToCart(name,size=selectedSize){const product=products.find(p=>p.name===name);const price=sizePrice(product,size);const found=cart.find(x=>x.name===name&&x.size===size);if(found)found.quantity+=qty;else cart.push({name,price,size,image:image(product),quantity:qty});localStorage.setItem('abid-cart',JSON.stringify(cart));updateCart();toast(`${name} added to your cart`);openCart()}
function openCart(){let panel=document.querySelector('.cart-panel');if(!panel){panel=document.createElement('aside');panel.className='cart-panel';document.body.append(panel)}panel.innerHTML=`<div class="cart-head"><h2>Your bag</h2><button class="icon-button close-cart">×</button></div>${cart.length?cart.map((item,i)=>`<div class="cart-item"><img src="${item.image}" alt="${item.name}"><div><h4>${item.name}</h4><p>${item.size || '50 ml'} · ${item.quantity} × ${money(item.price)}</p></div><button class="remove" data-remove="${i}">Remove</button></div>`).join('')+`<div class="cart-total"><strong>Subtotal</strong><strong>${money(cart.reduce((s,x)=>s+x.price*x.quantity,0))}</strong></div><a class="button" href="#checkout" data-route="checkout">Continue to checkout　→</a>`:'<div class="empty">Your bag is waiting for a signature scent.</div>'}`;panel.classList.add('open');panel.querySelector('.close-cart').onclick=()=>panel.classList.remove('open');panel.querySelector('[data-route]')?.addEventListener('click',()=>panel.classList.remove('open'));panel.querySelectorAll('[data-remove]').forEach(btn=>btn.onclick=()=>{cart.splice(+btn.dataset.remove,1);localStorage.setItem('abid-cart',JSON.stringify(cart));openCart();updateCart()})}
function bindPage(){
 document.querySelectorAll('[data-route]').forEach(el=>el.onclick=()=>{document.querySelector('.main-nav').classList.remove('open');document.querySelector('.cart-panel')?.classList.remove('open')});
 document.querySelectorAll('[data-product]').forEach(el=>el.onclick=()=>location.hash=`product/${encodeURIComponent(el.dataset.product)}`);
 document.querySelectorAll('[data-product-link]').forEach(el=>el.onclick=()=>location.hash=`product/${encodeURIComponent(el.dataset.productLink)}`);
 document.querySelectorAll('[data-add]').forEach(el=>el.onclick=()=>addToCart(el.dataset.add,selectedSize));
 document.querySelectorAll('[data-buy]').forEach(el=>el.onclick=()=>{addToCart(el.dataset.buy,selectedSize);location.hash='checkout'});
 document.querySelectorAll('.thumb').forEach(btn=>btn.onclick=()=>{document.querySelector('#main-product-image').src=image(currentProduct,+btn.dataset.index);document.querySelectorAll('.thumb').forEach(x=>x.classList.remove('active'));btn.classList.add('active')});
 document.querySelectorAll('.size').forEach(btn=>btn.onclick=()=>{selectedSize=btn.dataset.size||btn.textContent.trim();document.querySelectorAll('.size').forEach(x=>x.classList.remove('selected'));btn.classList.add('selected');const priceEl=document.querySelector('.detail-copy .price');if(priceEl)priceEl.textContent=money(sizePrice(currentProduct,selectedSize));});
 document.querySelectorAll('[data-quantity]').forEach(btn=>btn.onclick=()=>{qty=Math.max(1,qty+(btn.dataset.quantity==='+'?1:-1));document.querySelector('.qty-value').textContent=qty});
 const contact=document.querySelector('#contact-form');if(contact)contact.onsubmit=e=>{e.preventDefault();toast('Thank you. We will be in touch soon.');contact.reset()};
 const newsletter=document.querySelector('#newsletter-form');if(newsletter)newsletter.onsubmit=e=>{e.preventDefault();toast('You are now on the list.');newsletter.reset()};
 const track=document.querySelector('#tracking-form');if(track)track.onsubmit=e=>{e.preventDefault();document.querySelector('#track-result').classList.remove('hidden');document.querySelector('#track-result').innerHTML='<strong>Order received</strong><div class="track-line"><span>Order status</span><strong>Preparing for dispatch</strong></div><div class="track-line"><span>Estimated delivery</span><strong>2–5 working days</strong></div>'};
}
async function loadCatalog(){try{const response=await fetch('/api/products');if(!response.ok)return;const remote=await response.json();if(!remote.length)return;products=remote;render()}catch(_error){/* Direct file:// previews use the built-in catalog. */}}
document.addEventListener('submit',async event=>{if(event.target.id==='contact-form'){event.preventDefault();const form=event.target;const data=Object.fromEntries(new FormData(form));try{const response=await fetch('/api/contact',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const result=await response.json();if(!response.ok)throw new Error(result.message);toast(result.message);form.reset()}catch(_error){toast('Thank you. We will be in touch soon.');form.reset()}}if(event.target.id==='checkout-form'){event.preventDefault();const form=event.target;const data=Object.fromEntries(new FormData(form));const items=cart.map(item=>({name:item.name,price:item.price,quantity:item.quantity,size:item.size || '50 ml'}));const total=items.reduce((sum,item)=>sum+item.price*item.quantity,0);try{const response=await fetch('/api/orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({customer:{name:data['Full name'],phone:data['Phone number'],address:data['Delivery address']},items,total})});const result=await response.json();if(!response.ok)throw new Error(result.message);toast(`Order received: ${result.orderId}`);cart=[];localStorage.removeItem('abid-cart');form.reset();updateCart()}catch(_error){toast('Order details saved. We will contact you shortly.')}}},true);
function getSearchMatches(query){const term=query.trim().toLowerCase();if(!term)return products.slice(0,6);return products.filter(product=>[product.name,product.tag,product.description].some(text=>text.toLowerCase().includes(term))).slice(0,6)}
function renderSearchSuggestions(query=''){const shell=document.getElementById('search-shell');const input=document.getElementById('global-search-input');const suggestions=document.getElementById('search-suggestions');if(!shell||!input||!suggestions)return;const matches=getSearchMatches(query);if(!query.trim()){suggestions.innerHTML=`<div class="search-empty">Popular picks</div><div class="search-row">${products.slice(0,4).map(product=>`<button class="suggestion-item" type="button" data-product="${product.name}"><span>${product.name}</span><small>${product.tag}</small></button>`).join('')}</div>`;return;}if(!matches.length){suggestions.innerHTML='<div class="search-empty">No fragrance found. Try another name, tag, or scent note.</div>';return;}suggestions.innerHTML=`${matches.map(product=>`<button class="suggestion-item" type="button" data-product="${product.name}"><span>${product.name}</span><small>${product.tag}</small></button>`).join('')}`;suggestions.querySelectorAll('.suggestion-item').forEach(button=>{button.onclick=()=>{const productName=button.dataset.product;location.hash=`product/${encodeURIComponent(productName)}`;shell.classList.remove('open');input.value='';renderSearchSuggestions('');}})}
function runSearch(query){const term=query.trim();const matches=getSearchMatches(term);if(!term){toast('Please enter a product name or scent note.');return;}if(!matches.length){toast('No fragrance found.');renderSearchSuggestions(term);return;}if(matches.length===1){location.hash=`product/${encodeURIComponent(matches[0].name)}`;document.getElementById('search-shell')?.classList.remove('open');document.getElementById('global-search-input').value='';renderSearchSuggestions('');return;}renderSearchSuggestions(term);document.getElementById('search-shell')?.classList.add('open');}
document.querySelector('.cart-toggle').onclick=openCart;document.querySelector('.search-toggle').onclick=()=>{const shell=document.getElementById('search-shell');const input=document.getElementById('global-search-input');const isOpen=shell.classList.toggle('open');if(isOpen){input.focus();renderSearchSuggestions(input.value);return;}input.value='';renderSearchSuggestions('');};const searchInput=document.getElementById('global-search-input');if(searchInput){searchInput.addEventListener('input',event=>renderSearchSuggestions(event.target.value));searchInput.addEventListener('keydown',event=>{if(event.key==='Enter'){event.preventDefault();runSearch(event.target.value);}});document.querySelector('.search-submit')?.addEventListener('click',()=>runSearch(searchInput.value));document.querySelector('.search-clear')?.addEventListener('click',()=>{searchInput.value='';renderSearchSuggestions('');searchInput.focus();});}document.querySelector('.mobile-menu').onclick=()=>document.querySelector('.main-nav').classList.toggle('open');window.addEventListener('hashchange',render);render();loadCatalog();
